version: '3'


services:
  dvc_manager:
    privileged: true
    container_name: dvc_manager
    restart: always
    build: ./dvc_manager
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server --reload
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - HISTFILE=/dev/null
    volumes:
    - ./dvc_manager:/usr/src/dvc_manager
    - /etc/group:/etc/group
    - /etc/passwd:/etc/passwd
    - /etc/shadow:/etc/shadow
    - /home:/home


  client:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - dvc_manager

  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dvc_manager
      - client

  # db:
  #   image: postgres
  #   ports:
  #   - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Asdfghjkl-9151290
  #     POSTGRES_DB: poll_db
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #   volumes:
  #   - pgdata:/var/lib/postgresql/data