version: '3'


services:
  api:
    privileged: true
    container_name: api
    restart: always
    build: ./api
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b 0.0.0.0:5000 wsgi:server --reload
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - HISTFILE=/dev/null
    volumes:
    - ./api:/usr/src/api
    - /etc/group:/etc/group
    - /etc/passwd:/etc/passwd
    - /etc/shadow:/etc/shadow
    - /home:/home


  client:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client

  dvc_listener:
    container_name: dvc_listener
    restart: always
    build: ./dvc_listener
    ports:
      - "8080:8080"
    volumes: 
      - ./dvc_listener:/usr/src/dvc_listener
      - /home/ihoholko/tmp:/tmp



  # db:
  #   image: postgres
  #   ports:
  #   - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Asdfghjkl-9151290
  #     POSTGRES_DB: poll_db
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #   volumes:
  #   - pgdata:/var/lib/postgresql/data